export const sample_foods: any[] = [
    {
      id:'1',
      name: 'Pizza Pepperoni',
      cookTime: '10-20',
      price: 10,
      favorite: false,
      origins: ['Itália'],
      stars: 4.5,
      imageUrl: 'assets/food-1.jpg',
      tags: ['FastFood', 'Pizza', 'Almoço'],
    },
    {
      id:'2',
      name: 'Almôndega',
      price: 20,
      cookTime: '20-30',
      favorite: true,
      origins: ['Pérsia', 'Médio Oriente', 'China'],
      stars: 4.7,
      imageUrl: 'assets/food-2.jpg',
      tags: ['SlowFood', 'Almoço'],
    },
    {
      id:'3',
      name: 'Hamburger',
      price: 5,
      cookTime: '10-15',
      favorite: false,
      origins: ['Alemanha', 'Estados Unidos'],
      stars: 3.5,
      imageUrl: 'assets/food-3.jpg',
      tags: ['FastFood', 'Hamburger'],
    },
    {
      id:'4',
      name: 'Batatas fritas',
      price: 2,
      cookTime: '15-20',
      favorite: true,
      origins: ['Bélgica', 'França'],
      stars: 3.3,
      imageUrl: 'assets/food-4.jpg',
      tags: ['FastFood', 'Fritas'],
    },
    {
      id:'5',
      name: 'Caldo de galinha',
      price: 11,
      cookTime: '40-50',
      favorite: false,
      origins: ['Índia', 'Ásia'],
      stars: 3.0,
      imageUrl: 'assets/food-5.jpg',
      tags: ['SlowFood', 'Sopa'],
    },
    {
      id:'6',
      name: 'Pizza de Legumes',
      price: 9,
      cookTime: '40-50',
      favorite: false,
      origins: ['Itália'],
      stars: 4.0,
      imageUrl: 'assets/food-6.jpg',
      tags: ['FastFood', 'Pizza', 'Almoço'],
    },
  ]

  export const sample_tags: any[] = [
    { name: 'Todas', count: 6 },
    { name: 'FastFood', count: 4 },
    { name: 'Pizza', count: 2 },
    { name: 'Almoço', count: 3 },
    { name: 'SlowFood', count: 2 },
    { name: 'Hamburger', count: 1 },
    { name: 'Fritas', count: 1 },
    { name: 'Sopa', count: 1 },
  ]

  export const sample_users: any[] = [
    {
      name: "John Doe",
      email: "john@gmail.com",
      password: "12345",
      address: "Toronto On",
      isAdmin: true,
    },
    {
      name: "Jane Doe",
      email: "jane@gmail.com",
      password: "12345",
      address: "Shanghai",
      isAdmin: false,
    },
  ];